using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace FedFor01.Controllers
{
    public class Activities
    {
        public static IEnumerable<SelectListItem> ActivityListItems()
        {
            var items = new List<SelectListItem>
            {
                new SelectListItem() {Value = "AUTO TOURING", Text = "Auto Touring"},
                new SelectListItem() {Value = "BIKING", Text = "Biking"},
                new SelectListItem() {Value = "BOATING", Text = "Boating"},
                new SelectListItem() {Value = "CLIMBING", Text = "Climbing"},
                new SelectListItem() {Value = "HISTORIC & CULTURAL SITE", Text = "Historical/Cultural Site"},
                new SelectListItem() {Value = "CAMPING", Text = "Camping"},
                new SelectListItem() {Value = "INTERPRETIVE PROGRAMS", Text = "Interpretive Programs"},
                new SelectListItem() {Value = "FISHING", Text = "Fishing"},
                new SelectListItem() {Value = "HIKING", Text = "Hiking"},
                new SelectListItem() {Value = "HORSEBACK RIDING", Text = "Horseback Riding"},
                new SelectListItem() {Value = "HUNTING", Text = "Hunting"},
                new SelectListItem() {Value = "OFF HIGHWAY VEHICLE", Text = "Off-Highway Vehicle"},
                new SelectListItem() {Value = "PICNICKING", Text = "Picnicking"},
                new SelectListItem() {Value = "WINTER SPORTS", Text = "Winter Sports"},
                new SelectListItem() {Value = "RECREATIONAL VEHICLES", Text = "Recreational Vehicles"},
                new SelectListItem() {Value = "VISITOR CENTER", Text = "Visitor Center"},
                new SelectListItem() {Value = "WATER SPORTS", Text = "Water Sports"},
                new SelectListItem() {Value = "WILDLIFE VIEWING", Text = "Wildlife Viewing"},
                new SelectListItem() {Value = "FISH HATCHERY", Text = "Fish Hatchery"},
                new SelectListItem() {Value = "WILDERNESS", Text = "Wilderness"},
                new SelectListItem() {Value = "FIRE LOOKOUTS/CABINS OVERNIGHT", Text = "Fire Lookouts/Cabins Overnight"},
                new SelectListItem() {Value = "FISH VIEWING SITE", Text = "Fish Viewing Site"},
                new SelectListItem() {Value = "DAY USE AREA", Text = "Day Use Area"},
                new SelectListItem() {Value = "DOCUMENTARY SITE", Text = "Documentary Site"},
                new SelectListItem() {Value = "SWIMMING SITE", Text = "Swimming Site"},
                new SelectListItem() {Value = "ORGANIZATION SITE PRIVATELY OWNED", Text = "Organization Site is Privately Owned"},
                new SelectListItem() {Value = "ORGANIZATION SITE FS OWNED", Text = "Organization Site is FS(?) Owned"},
                new SelectListItem() {Value = "PLAYGROUND PARK SPECIALIZED SPORT SITE", Text = "Playground Park Specialized Sport Site"},
                new SelectListItem() {Value = "OTHER RECREATION CONCESSION SITE", Text = "Other Recreation Concession Site"},
                new SelectListItem() {Value = "OBSERVATION SITE", Text = "Observation Site"},
                new SelectListItem() {Value = "HOTEL/LODGE/RESORT FS OWNED", Text = "Hotel/Lodge/Resort FS(?) Owned"},
                new SelectListItem() {Value = "INFORMATION SITE", Text = "Information Site"},
                new SelectListItem() {Value = "RECREATION RESIDENCE", Text = "Recreation Residence"},
                new SelectListItem() {Value = "SNOWPARK", Text = "Snowpark"},
                new SelectListItem() {Value = "HOTEL/LODGE/RESORT PRIVATELY OWNED", Text = "Hotel/Lodge/Resort is Privately Owned"},
                new SelectListItem() {Value = "ENVIRONMENTAL EDUCATION", Text = "Environmental Education"},
                new SelectListItem() {Value = "PHOTOGRAPHY", Text = "Photography"},
                new SelectListItem() {Value = "PADDLING", Text = "Paddling"},
                new SelectListItem() {Value = "SWIMMING", Text = "Swimming"},
                new SelectListItem() {Value = "DIVING", Text = "Diving"},
                new SelectListItem() {Value = "SNORKELING", Text = "Snorkeling"},
                new SelectListItem() {Value = "HORSE CAMPING", Text = "Horse Camping"},
                new SelectListItem() {Value = "RECREATIONAL SHOOTING", Text = "Recreation Shooting"},
                new SelectListItem() {Value = "MOTOR BOAT", Text = "Motor Boating"},
                new SelectListItem() {Value = "SNOWMOBILE", Text = "Snowmobiles"},
                new SelectListItem() {Value = "MOUNTAIN BIKING", Text = "Mountain Biking"},
                new SelectListItem() {Value = "OFF ROAD VEHICLE TRAILS", Text = "Off Road Vehicle Trails"},
                new SelectListItem() {Value = "RANGER STATION", Text = "Ranger Station"},
                new SelectListItem() {Value = "PADDLE BOATING", Text = "Paddle Boating"},
                new SelectListItem() {Value = "WATER ACTIVITIES", Text = "Water Activities"},
                new SelectListItem() {Value = "KAYAKING", Text = "Kayaking"},
                new SelectListItem() {Value = "CANOEING", Text = "Canoeing"},
                new SelectListItem() {Value = "BERRY PICKING", Text = "Berry Picking"},
                new SelectListItem() {Value = "BEACH CAMPING", Text = "Beach Camping"},
                new SelectListItem() {Value = "BEACHCOMBING", Text = "Beachcombing"},
                new SelectListItem() {Value = "CLAM DIGGING", Text = "Clam Digging"},
                new SelectListItem() {Value = "CRABBING", Text = "Crabbing"},
                new SelectListItem() {Value = "SEA KAYAKING", Text = "Sea Kayaking"},
                new SelectListItem() {Value = "STAR GAZING", Text = "Star Gazing"},
                new SelectListItem() {Value = "SURFING", Text = "Surfing"},
                new SelectListItem() {Value = "BIRDING", Text = "Birding"},
                new SelectListItem() {Value = "NON-MOTORIZED BOATING", Text = "Non-motorized Boating"},
                new SelectListItem() {Value = "WATER ACCESS", Text = "Water Access"},
                new SelectListItem() {Value = "CROSS COUNTRY SKIING", Text = "Cross Country Skiing"},
                new SelectListItem() {Value = "ANTIQUING", Text = "Antiquing"},
                new SelectListItem() {Value = "JET SKIING", Text = "Jet Skiing"},
                new SelectListItem() {Value = "WATER SKIING", Text = "Water Skiing"},
                new SelectListItem() {Value = "DISC GOLF", Text = "Disc Golf"},
                new SelectListItem() {Value = "CULTURAL ACTIVITIES", Text = "Cultural Activities"},
                new SelectListItem() {Value = "EVENING PROGRAMS", Text = "Evening Programs"},
                new SelectListItem() {Value = "GUIDED INTERPRETIVE WALKS", Text = "Guided Interpretive Walks"},
                new SelectListItem() {Value = "RECREATION PROGRAMS", Text = "Recreation Programs"},
                new SelectListItem() {Value = "SCENIC DRIVE", Text = "Scenic Drive"},
                new SelectListItem() {Value = "WINDSURFING", Text = "Windsurfing"},
                new SelectListItem() {Value = "GOLD PANNING", Text = "Gold Panning"},
                new SelectListItem() {Value = "RAFTING", Text = "Rafting"},
                new SelectListItem() {Value = "RIVER TRIPS", Text = "River Trips"},
                new SelectListItem() {Value = "WHITEWATER RAFTING", Text = "Whitewater Rafting"},
                new SelectListItem() {Value = "ICE CLIMBING", Text = "Ice Climbing"},
                new SelectListItem() {Value = "BACKPACKING", Text = "Backpacking"},
                new SelectListItem() {Value = "SAILING", Text = "Sailing"},
                new SelectListItem() {Value = "SCUBA DIVING", Text = "Scuba Diving"},
                new SelectListItem() {Value = "WHALE WATCHING", Text = "Whale Watching"},
                new SelectListItem() {Value = "MOUNTAIN CLIMBING", Text = "Mountain Climbing"},
                new SelectListItem() {Value = "ROCK CLIMBING", Text = "Rock Climbing"},
                new SelectListItem() {Value = "MUSHROOM PICKING", Text = "Mushroom Picking"},
                new SelectListItem() {Value = "AMPHITHEATER", Text = "Amphitheater"},
                new SelectListItem() {Value = "EDUCATIONAL PROGRAMS", Text = "Educational Programs"},
                new SelectListItem() {Value = "TUBING", Text = "Tubing"},
                new SelectListItem() {Value = "SNOWSHOEING", Text = "Snowshoeing"},
                new SelectListItem() {Value = "ARCHERY", Text = "Archery"},
                new SelectListItem() {Value = "HISTORIC SITES", Text = "Historic Sites"},
                new SelectListItem() {Value = "ACCESSIBLE SWIMMING", Text = "Accessible Swimming"},
                new SelectListItem() {Value = "SOFTBALL FIELDS", Text = "Softball Fields"},
                new SelectListItem() {Value = "SNOWMOBILING", Text = "Snowmobiling"},
                new SelectListItem() {Value = "LOOKOUT TOWER", Text = "Lookout Tower"},
                new SelectListItem() {Value = "SLEDDING", Text = "Sledding"},
                new SelectListItem() {Value = "DOWNHILL SKIING", Text = "Downhill Skiing"},
                new SelectListItem() {Value = "SKIING", Text = "Skiing"},
                new SelectListItem() {Value = "SNOWMOBILE TRAILS", Text = "Snowmobile Trails"},
                new SelectListItem() {Value = "SNOWBOARDING", Text = "Snowboarding"},
                new SelectListItem() {Value = "WOOD CUTTING", Text = "Wood Cutting"},
                new SelectListItem() {Value = "ICE FISHING", Text = "Ice Fishing"},
                new SelectListItem() {Value = "CRAWFISHING", Text = "Crawfishing"},
                new SelectListItem() {Value = "BIRD WATCHING", Text = "Bird Watching"},
                new SelectListItem() {Value = "WILD HORSE VIEWING", Text = "Wild Horse Viewing"},
                new SelectListItem() {Value = "OFF HIGHWAY VEHICLE TRAILS", Text = "Off Highway Vehicle Trails"},
                new SelectListItem() {Value = "BADMINTON", Text = "Badminton"},
                new SelectListItem() {Value = "PICNIC TABLES", Text = "Picnic Tables"},
                new SelectListItem() {Value = "HIKING TRAIL", Text = "Hiking Trail"},
                new SelectListItem() {Value = "ICE SKATING", Text = "Ice Skating"},
                new SelectListItem() {Value = "SNOW TUBING", Text = "Snow Tubing"},
                new SelectListItem() {Value = "MARINA", Text = "Marina"},
                new SelectListItem() {Value = "SOCCER FIELDS", Text = "Soccer Fields"},
                new SelectListItem() {Value = "EMERGENCY SERVICES", Text = "Emergency Services"},
                new SelectListItem() {Value = "MUSEUM", Text = "Museum"},
                new SelectListItem() {Value = "SAILBOARDING", Text = "Sailboarding"},
                new SelectListItem() {Value = "TRAILS, ALL TERRAIN/OHV", Text = "All Terrain Vehicle Trails"},
                new SelectListItem() {Value = "TRAILS, HORSE", Text = "Horse Trails"},
                new SelectListItem() {Value = "TRAILS, DIFFICULT HIKING", Text = "Difficult Hiking Trails"},
                new SelectListItem() {Value = "BOAT RENTAL", Text = "Boat Rental"},
                new SelectListItem() {Value = "GONDOLA RIDES", Text = "Gondola Rides"},
                new SelectListItem() {Value = "GOLF", Text = "Golf"},
                new SelectListItem() {Value = "CAVING", Text = "Caving"},
                new SelectListItem() {Value = "WINERY TOURS", Text = "Winery Tours"},
                new SelectListItem() {Value = "SHUFFLE BOARD", Text = "Shuffle Board"},
                new SelectListItem() {Value = "STARGAZING", Text = "Stargazing"},
                new SelectListItem() {Value = "MOTEL", Text = "Motel"},
            };
            return items;
        }
    }
}